# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Soulmesh' do
	pod "MMMaterialDesignSpinner"
	pod "AFNetworking", "~> 2.0"
	pod "MagicalRecord"
	pod "SwiftyJSON"
end

target 'SoulmeshTests' do

end

target 'SoulmeshUITests' do

end

